version: "3.8"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
